version: 1.0.{build}
shallow_clone: true
build:
  verbosity: minimal

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
      COMPILER: "Microsoft Visual Studio 14.0"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015 Win64"
      COMPILER: "Microsoft Visual Studio 14.0"
      CONFIG: Release

artifacts:
  - path: dist
    name: Truss_v${APPVEYOR_BUILD_VERSION}_${CONFIG}_Win
    type: zip

before_build:
  # Remove unused Xamarin targets to decrease log spam.
  # See: http://help.appveyor.com/discussions/problems/4569
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - ctest -VV -C "%CONFIG%"

###################
# Debugging Tools #
###################
## This adds RDP access to the build VM, which is useful for debugging.
## See: http://www.appveyor.com/docs/how-to/rdp-to-build-worker
# init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

## This blocks VM termination until a file is manually deleted on the VM
## allowing time for RDP debugging (60 min build timeout still applies).
## See: http://www.appveyor.com/docs/how-to/rdp-to-build-worker
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
