language: cpp

os:
  - linux
  - osx

env:
  matrix:
    - CONFIG=Debug
    - CONFIG=Release

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script:
  - make test
  - zip -r "truss_${TRAVIS_TAG}_${TRAVIS_OS_NAME}_${CONFIG}.zip" dist/

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "truss_${TRAVIS_TAG}_${TRAVIS_OS_NAME}_${CONFIG}.zip"
  skip_cleanup: true
  on:
    tags: true
