# Builds and runs tests

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install luajit on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install -qq -y luajit
          
      # Run luajit build script
      - name: CI Build
        run: luajit _build/cibuild.lua

      # Run tests
      - name: Run tests
        run: ./truss dev/test.t
