name: Release Trimesh

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run CMake
      run: |
        ls
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=release
    - name: Build
      run: |
        cd build
        make
